"""HypoStore 계약 — 프론트가 의존하는 데이터 인터페이스 (Mock/Backend 교체 지점).

다중 프로젝트 지원: 프로젝트 목록/생성 + 프로젝트별 가설.
"""
from __future__ import annotations

from typing import Iterator, List, Protocol, Tuple, runtime_checkable

from src.api.types import Project, Hypothesis, AgentEvent


@runtime_checkable
class HypoStore(Protocol):
    def list_projects(self) -> List[Project]: ...
    def create_project(self, name: str) -> Project: ...
    def rename_project(self, project_id: str, name: str) -> Project: ...
    def delete_project(self, project_id: str) -> None: ...
    def list_hypotheses(self, project_id: str) -> List[Hypothesis]: ...
    def create_hypothesis(self, project_id: str, content: str,
                          max_experiments: int, parallel_count: int) -> Hypothesis: ...
    def delete_hypothesis(self, hypothesis_id: str) -> None: ...
    def run(self, hypothesis_id: str) -> Iterator[AgentEvent]: ...
    def start_run(self, hypothesis_id: str) -> None: ...
    def get_report(self, hypothesis_id: str) -> Hypothesis: ...
    def best_scores(self, project_id: str) -> List[Tuple[Hypothesis, float]]: ...
